spring:
  datasource:
    username: triet
    password: minhtriet123
    url: jdbc:mysql://blog-db-1.cfwwccq0en65.ap-southeast-2.rds.amazonaws.com:3306/blog_app_apis
# phai dung password voi ben MySQL Workbench
#    url: jdbc:mysql://blog-db.cfwwccq0en65.ap-southeast-2.rds.amazonaws.com:3306/blog_app_apis